-- Auto generated by VS Code
fx_version 'cerulean'
game 'gta5'

name "spawnped"
description "Example resource to spawn a specified ped with a specified weapon and specified hostility towards the player"
author "Asaayu"
version "1.0.0"

client_scripts {
	'client/main.lua'
}
